"""
Gemini image generation with reference-image conditioning.

This is the consistency cornerstone: panel art is generated by passing the
character's approved reference image(s) alongside the text prompt, so the same
character renders the same way across panels and parts. Returns normalised PNG
bytes; persistence is the caller's job (storage.store_asset).

Ported and generalised from linkedin-infographic/image_generator.py.
"""

import random
import time
from io import BytesIO

from PIL import Image

from .. import config
from . import errors

_client = None


def _get_client():
    global _client
    if _client is None:
        from google import genai

        if not config.GEMINI_API_KEY:
            raise errors.ApiKeyMissingError("GEMINI_API_KEY is not set")
        _client = genai.Client(api_key=config.GEMINI_API_KEY)
    return _client


def _extract_image_bytes(response) -> bytes:
    """Pull raw image bytes out of a Gemini generate_content response."""
    if not response.candidates:
        reason = getattr(getattr(response, "prompt_feedback", None), "block_reason", None)
        raise errors.ContentPolicyError(
            f"Gemini blocked the request before generating (block_reason={reason}). "
            "Try rephrasing the prompt."
        )

    candidate = response.candidates[0]
    finish_reason = str(getattr(candidate, "finish_reason", "UNKNOWN"))
    if finish_reason in ("SAFETY", "RECITATION"):
        raise errors.ContentPolicyError(
            f"Gemini refused image generation (finish_reason={finish_reason}). "
            "Try simplifying descriptions or avoiding specific names/brands."
        )
    if not candidate.content or not candidate.content.parts:
        raise errors.ImageGenerationError(
            f"Gemini response has no content parts (finish_reason={finish_reason})."
        )
    for part in candidate.content.parts:
        if getattr(part, "inline_data", None) is not None and part.inline_data.data:
            return part.inline_data.data
    raise errors.ImageGenerationError(
        f"No image part in Gemini response (finish_reason={finish_reason}); "
        "the model may have returned only text."
    )


def _to_png_bytes(raw: bytes) -> bytes:
    img = Image.open(BytesIO(raw))
    if img.mode not in ("RGB", "RGBA"):
        img = img.convert("RGB")
    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def generate_image(
    prompt: str,
    *,
    reference_images: list[bytes] | None = None,
    verbose: bool = False,
) -> bytes:
    """
    Generate an image from `prompt`, optionally conditioned on reference images.

    Args:
        prompt: the assembled text prompt (no embedded text rendering for panels).
        reference_images: raw image bytes (PNG/JPEG) to anchor character / style
            consistency. Each is passed to Gemini as an input image.

    Returns:
        PNG bytes.
    """
    client = _get_client()
    refs = reference_images or []
    last_error: Exception | None = None

    for attempt in range(1, config.MAX_RETRIES + 1):
        try:
            from google.genai import types  # noqa: F401  (ensures SDK import path)

            contents: list = [prompt]
            for raw in refs:
                # PIL Image objects are accepted directly as input images and are
                # robust across google-genai versions.
                contents.append(Image.open(BytesIO(raw)))

            response = client.models.generate_content(
                model=config.GEMINI_IMAGE_MODEL,
                contents=contents,
                config=types.GenerateContentConfig(
                    response_modalities=config.IMAGE_RESPONSE_MODALITIES,
                ),
            )
            return _to_png_bytes(_extract_image_bytes(response))

        except (errors.ContentPolicyError, errors.ModelNotFoundError):
            raise
        except errors.ImageGenerationError as e:
            last_error = e
            if attempt < config.MAX_RETRIES:
                wait = (config.RETRY_BACKOFF_BASE ** attempt) + random.uniform(0, 1)
                if verbose:
                    print(f"  image attempt {attempt} failed: {e}; retry in {wait:.1f}s")
                time.sleep(wait)
        except Exception as e:
            s = str(e).lower()
            if "429" in s or "quota" in s or "rate" in s:
                last_error = errors.RateLimitError(str(e))
                if attempt < config.MAX_RETRIES:
                    time.sleep((config.RETRY_BACKOFF_BASE ** attempt) + random.uniform(0, 1))
                else:
                    raise last_error from e
            elif "not found" in s or "404" in s:
                raise errors.ModelNotFoundError(
                    f"Model '{config.GEMINI_IMAGE_MODEL}' not found: {e}"
                ) from e
            else:
                last_error = errors.ImageGenerationError(f"Unexpected error: {e}")
                if attempt < config.MAX_RETRIES:
                    time.sleep(config.RETRY_BACKOFF_BASE ** attempt)

    raise last_error or errors.ImageGenerationError("Image generation failed")
